# Generated by Django 3.1.1 on 2020-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('main_photo', models.ImageField(upload_to='%Y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
