# Generated by Django 3.1.1 on 2020-09-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва товару')),
                ('price', models.IntegerField(max_length=12, verbose_name='Ціна товару')),
                ('color', models.CharField(max_length=20, verbose_name='Колір')),
                ('description', models.TextField(max_length=250, verbose_name='Опис товару')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
