# Generated by Django 3.1.1 on 2020-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200902_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Додати товар у магазин', 'verbose_name_plural': 'Додати товар у магазин'},
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сума у гривнях', verbose_name='Ціна товару'),
        ),
    ]
